# Generated by Django 4.1.7 on 2023-04-01 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Phone_number', message='Length has to be 10', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='reginster_number',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Register_number', message='Length has to be 12', regex='^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_passing',
            field=models.IntegerField(default=2024, validators=[django.core.validators.RegexValidator(code='Invalid Register_number', message='Length has to be 4', regex='^\\d{4}$')]),
        ),
    ]
