# Generated by Django 4.1.7 on 2023-04-01 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_last_name_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Phone_number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('reginster_number', models.IntegerField(default=0, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Register_number', message='Length has to be 12', regex='^\\d{12}$')])),
                ('department', models.CharField(blank=True, max_length=30)),
                ('year_of_passing', models.IntegerField(default=2024, validators=[django.core.validators.RegexValidator(code='Invalid Register_number', message='Length has to be 4', regex='^\\d{4}$')])),
            ],
        ),
    ]
